CREATE TABLE IF NOT EXISTS `Session` (
    `Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `SessionId` NVARCHAR(1000) NULL,
    `Created` DATETIME NULL,
    `LastUpdated` DATETIME NULL,
    `EventYear` NVARCHAR(200) NOT NULL,
    `EventName` NVARCHAR(8000) NULL,
    `Starts` NVARCHAR(8000) NULL,
    `Finish` NVARCHAR(8000) NULL,
    `Title` NVARCHAR(8000) NULL,
    `Description` NVARCHAR(8000) NULL,
    `Speakerids` NVARCHAR(8000) NULL,
    `Link` NVARCHAR(8000) NULL,
    `Slides` NVARCHAR(8000) NULL,
    `Tags` NVARCHAR(8000) NULL,
    `Code` NVARCHAR(8000) NULL,
    `Level` NVARCHAR(8000) NULL,
    `Track` NVARCHAR(8000) NULL,
    `SessionType` NVARCHAR(8000) NULL,
    `Mediaduration` NVARCHAR(8000) NULL,
    `Iskeynote` BIT NOT NULL,
    `Prerecorded` BIT NOT NULL,
    `Notrecorded` BIT NOT NULL,
    `Previewimage` NVARCHAR(8000) NULL,
    `Thumbnailimage` NVARCHAR(8000) NULL,
    `Video` NVARCHAR(8000) NULL,
    `Mp4med` NVARCHAR(8000) NULL,
    `Mp4high` NVARCHAR(8000) NULL,
    `Mp4low` NVARCHAR(8000) NULL,
    `Wmvhq` NVARCHAR(8000) NULL,
    `Wmv` NVARCHAR(8000) NULL,
    `Smooth` NVARCHAR(8000) NULL,
    `Room` NVARCHAR(8000) NULL
);

